name: CI

on:
  push:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            lint: true
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    env:
      TERM: xterm-256color

    steps:
      - name: Install Crystal
        uses: oprypin/install-crystal@v1

      - name: Donwload sources
        uses: actions/checkout@v2

      - name: Check formatting
        if: ${{ matrix.lint  }}
        run: crystal tool format --check

      - name: Install dependencies
        run: shards install

      - name: Run linter
        if: ${{ matrix.lint  }}
        run: ./bin/ameba

      - name: Setup environment
        run: crystal examples/sam.cr setup

      - name: Run specs
        run: crystal spec
